CREATE TABLE IF NOT EXISTS orders (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  fullname VARCHAR(32) NOT NULL,
  title VARCHAR(256) NOT NULL,
  quantity INTEGER DEFAULT 1,
  address VARCHAR(256) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  register_date DATE DEFAULT CURRENT_DATE
);

CREATE TABLE IF NOT EXISTS books (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title VARCHAR(256) NOT NULL, 
  quantity INTEGER NOT NULL,
  author VARCHAR(32)
);